services:
  postgres:
    image: 'postgres:latest'
    container_name: 'expensetracker-postgres'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USERNAME}'
      - 'POSTGRES_DB=expensetracker'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  spring-app:
    image: 'jacobarthurs/expensetracker:latest'
    container_name: 'expensetracker-spring-app'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/expensetracker'
      - 'SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}'
      - 'SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}'
      - 'SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}'
      - 'SECRET_KEY=${SECRET_KEY}'

volumes:
  postgres-data: