services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=expense_tracker'
      - 'POSTGRES_PASSWORD=password'